### ISSUE TITLE
error[E0407]: method `source` is not a member of trait `Error`

### ISSUE THREAD

**Issue by pjedge** [cpearce/fishers_exact#3]
I can't get the library to compile using rust 1.29.2.
```
error[E0407]: method `source` is not a member of trait `Error`
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/fishers_exact-1.0.1/src/lib.rs:213:5
    |
213 | /     fn source(&self) -> Option<&(dyn Error + 'static)> {
214 | |         None
215 | |     }
    | |_____^ not a member of trait `Error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0407`.
error: Could not compile `fishers_exact`.
```

**Comment by cpearce** [comment]
Thanks for the bug report! I'll take a look as soon as I get a chance.

**Comment by pjedge** [comment]
Actually, the issue went away just by updating to rust 1.32.0.
